# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
# You can delete data by using 'rails console' then 'modelname.destroy_all'
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Article.create(:title => 'Introduction', :points => 0)
Article.create(:title => 'Food Scale', :points => 1)
Article.create(:title => 'Reading a Nutritional Label', :points => 3)
Article.create(:title => 'Calories', :points => 6)
Article.create(:title => 'Water', :points => 8)
Article.create(:title => 'Fat', :points => 10)
Article.create(:title => 'Carbs', :points => 12)
Article.create(:title => 'Fiber', :points => 13)
Article.create(:title => 'Protein', :points => 14)
Article.create(:title => 'What Is Hunger?', :points => 15)
Article.create(:title => 'When To Eat?', :points => 16)
Article.create(:title => 'Exercise', :points => 17)
Article.create(:title => 'Why Measure Eating?', :points => 18)
Article.create(:title => 'What Is Healthy Eating?', :points => 21)
Article.create(:title => 'Fruits & Veggies', :points => 23)
Article.create(:title => 'Drinking Calories', :points => 26)
Article.create(:title => 'Addictive Foods', :points => 27)
Article.create(:title => 'Importance of Cookies', :points => 31)
Article.create(:title => 'Social Events', :points => 35)
Article.create(:title => 'Alcohol', :points => 36)
Article.create(:title => 'Health Effects of High Fat vs Healthy Weight', :points => 41)
Article.create(:title => 'Supplements', :points => 43)
Article.create(:title => 'Long-Term Attitude', :points => 51)
Article.create(:title => 'What Is Weight Loss?', :points => 53)
